php_version: 7.0

php:
  ini:
    post_max_size: '16M'
    upload_max_filesize: '16M'
    max_file_uploads: '20'
    memory_limit: '128M'
    timezone: "Europe/Paris"
    error_reporting: 'E_ALL & ~E_DEPRECATED & ~E_STRICT'

php_extensions:
  - "cli"
  - "mysql"
  - "pgsql"
  - "sqlite3"
  - "gd"
  - "curl"
  - "memcached"
  - "intl"
  - "xmlrpc"
#  - "redis"
#  - "apcu"

apache_vhosts:
  site1:
    vhost_docroot: '/var/www'
    vhost_name: 'varnish.dev'
    vhost_options: 'All'
    vhost_port: '8080'

mysql:
  root_password: 'vagrant'
  sites:
    site1:
      db_name: 'db_site1'
      db_user: 'vagrant'
      db_password: 'vagrant'

varnish_port: 80
apache_port: 8080

symfony: true
composer: true
